modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Library/issues"
license = "All Rights Reserved"

[[mods]]
modId = "ftblibrary"
version = "${version}"
displayName = "FTB Library"
authors = "LatvianModder"
description = '''
FTB Library adds nothing.
'''

[[dependencies.ftblibrary]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftblibrary]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftblibrary]]
modId = "architectury"
mandatory = true
versionRange = "[5.5.16,)"
ordering = "AFTER"
side = "BOTH"
