modLoader="javafml"
loaderVersion="[30,)"
issueTrackerURL = "https://github.com/FTBTeam/FTB-GUI-Library/issues"
license = "All Rights Reserved"

[[mods]]
modId="ftbguilibrary"
version="${file.jarVersion}"
displayName="FTB GUI Library"
authors="LatvianModder"
description= '''
FTB GUI Library adds nothing.
'''

[[dependencies.ftbguilibrary]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ftbguilibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,)"
    ordering="NONE"
    side="BOTH"
